repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: no-commit-to-branch
      args: [--branch, main]
    - id: requirements-txt-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: [--profile, black]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.1
  hooks:
    - id: pyupgrade
      args: [--py37-plus]
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
   - id: flake8
     additional_dependencies: [flake8-typing-imports==1.7.0]
     args: ['--ignore=E501,E203,E731,W503']
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
